version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: barbersystem_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongodb_consumer:
    image: mongo:4.4
    container_name: barbersystem_mongodb_consumer
    volumes:
      - mongodb_data:/data/db
    command: ["tail", "-f", "/dev/null"]

volumes:
  mongodb_data: